export const SEED_PROPERTIES = [
  {
    slug: "chianti-pavilion-01",
    name: "Chianti The Pavilion - Unit A",
    phase: "Phase 13",
    estate: "Chianti",
    property_type: "Flat",
    beds: 4, baths: 4,
    gross_sqft: 2248, net_sqft: 1730,
    price: 15000000,
    psf_gross: 6674, psf_net: 8671,
    deal_score: 35,
    status: "listing",
    features: ["4 ensuite bedrooms", "balcony", "open bar kitchen", "spacious layout"],
    listing_urls: [
      { site: "Spacious", url: "https://www.spacious.hk/en/hong-kong/n/28-discovery-bay/b/64748--the-pavilion-chianti-f5189c7c-1fdc-4043-9130-6233c35eaf66" },
      { site: "OKAY.com", url: "https://www.okay.com/en/building/chianti-the-pavilion-block-1/6591" }
    ],
    image_url: null,
  },
  {
    slug: "chianti-pavilion-02",
    name: "Chianti The Pavilion - Unit B",
    phase: "Phase 13",
    estate: "Chianti",
    property_type: "Flat",
    beds: 4, baths: 4,
    gross_sqft: 2248, net_sqft: 1729,
    price: 16000000,
    psf_gross: 7118, psf_net: 9254,
    deal_score: 31,
    status: "listing",
    features: ["4 ensuite bedrooms", "premium location", "sky garden"],
    listing_urls: [
      { site: "OKAY.com", url: "https://www.okay.com/en/building/chianti-the-pavilion-block-1/6591" }
    ],
    image_url: null,
  },
  {
    slug: "la-serene-large",
    name: "La Serene - Serene Court (Larger)",
    phase: "Phase 9",
    estate: "La Serene",
    property_type: "Flat",
    beds: 3, baths: 2,
    gross_sqft: 1408, net_sqft: 1203,
    price: 10500000,
    psf_gross: 7460, psf_net: 8729,
    deal_score: 28,
    status: "listing",
    features: ["serene setting", "water feature", "low-rise", "children's area"],
    listing_urls: [
      { site: "Spacious", url: "https://www.spacious.hk/en/hong-kong/n/28-discovery-bay/b/5335--la-serene" },
      { site: "28Hse", url: "https://www.28hse.com/en/estate/detail/discovery-bay-la-serene-24518" }
    ],
    image_url: null,
  },
  {
    slug: "la-serene-small",
    name: "La Serene - Compact Unit",
    phase: "Phase 9",
    estate: "La Serene",
    property_type: "Flat",
    beds: 3, baths: 2,
    gross_sqft: 1188, net_sqft: 1012,
    price: 10500000,
    psf_gross: 8838, psf_net: 10376,
    deal_score: 14,
    status: "listing",
    features: ["entry-level price", "low-rise", "garden views"],
    listing_urls: [
      { site: "Spacious", url: "https://www.spacious.hk/en/hong-kong/n/28-discovery-bay/b/5335--la-serene" }
    ],
    image_url: null,
  },
  {
    slug: "peninsula-coastline",
    name: "Peninsula Village - Coastline Villa",
    phase: "Phase 4",
    estate: "Peninsula Village",
    property_type: "Villa-style Flat",
    beds: 3, baths: 2,
    gross_sqft: 1508, net_sqft: 1314,
    price: 12500000,
    psf_gross: 8287, psf_net: 9514,
    deal_score: 20,
    status: "listing",
    features: ["villa style", "sea/marina views", "low-rise", "largest 3BR in DB"],
    listing_urls: [
      { site: "Spacious", url: "https://www.spacious.hk/en/hong-kong/n/28-discovery-bay/b/115502--coastline-villa-527951d5-6e88-4cad-97d0-b3bec5fe0636" },
      { site: "OKAY.com", url: "https://www.okay.com/en/building/peninsula-village-coastline-villa/3272" }
    ],
    image_url: null,
  },
  {
    slug: "neo-horizon",
    name: "Neo Horizon",
    phase: "Phase 10",
    estate: "Neo Horizon",
    property_type: "Flat",
    beds: 3, baths: 2,
    gross_sqft: 1545, net_sqft: 1213,
    price: 14000000,
    psf_gross: 9065, psf_net: 11541,
    deal_score: 12,
    status: "listing",
    features: ["high-rise", "art deco", "HK Island views", "Siena Park views", "fresh listing"],
    listing_urls: [
      { site: "Spacious", url: "https://www.spacious.hk/en/hong-kong/n/28-discovery-bay/b/19070--neo-horizon-i" },
      { site: "OKAY.com", url: "https://www.okay.com/en/building/neo-horizon/3305" }
    ],
    image_url: null,
  },
  {
    slug: "siena-one-large",
    name: "Siena One - Larger Unit",
    phase: "Phase 11",
    estate: "Siena One",
    property_type: "Flat",
    beds: 3, baths: 2,
    gross_sqft: 1658, net_sqft: 1326,
    price: 15500000,
    psf_gross: 9350, psf_net: 11685,
    deal_score: 9,
    status: "listing",
    features: ["lakeside", "updated listing Feb 2026"],
    listing_urls: [
      { site: "Spacious", url: "https://www.spacious.hk/en/hong-kong/n/28-discovery-bay/b/64983--siena-one-6c6250ac-7525-4486-a83a-64e9f3ba1c01" }
    ],
    image_url: null,
  },
  {
    slug: "siena-one-seaview",
    name: "Siena One - Sea View",
    phase: "Phase 11",
    estate: "Siena One",
    property_type: "Flat",
    beds: 3, baths: 2,
    gross_sqft: 1432, net_sqft: 1146,
    price: 15000000,
    psf_gross: 10474, psf_net: 13088,
    deal_score: -2,
    status: "listing",
    features: ["sea view", "premium position"],
    listing_urls: [
      { site: "Spacious", url: "https://www.spacious.hk/en/hong-kong/n/28-discovery-bay/b/64983--siena-one-6c6250ac-7525-4486-a83a-64e9f3ba1c01" }
    ],
    image_url: null,
  },
  {
    slug: "chianti-premier",
    name: "Chianti The Premier",
    phase: "Phase 13",
    estate: "Chianti",
    property_type: "Flat",
    beds: 3, baths: 3,
    gross_sqft: 1755, net_sqft: 1755,
    price: 18800000,
    psf_gross: 10712, psf_net: 10712,
    deal_score: -4,
    status: "listing",
    features: ["waterfront", "3 bathrooms", "generous layout"],
    listing_urls: [
      { site: "Spacious", url: "https://www.spacious.hk/en/hong-kong/n/28-discovery-bay/b/64750--the-premier-chianti-8255f5c5-3817-4aee-9ce5-5144683c8b58" }
    ],
    image_url: null,
  },
  {
    slug: "poggibonsi",
    name: "Poggibonsi",
    phase: "Phase 16",
    estate: "Poggibonsi",
    property_type: "Flat",
    beds: 3, baths: 2,
    gross_sqft: 1380, net_sqft: 1380,
    price: 19800000,
    psf_gross: 14348, psf_net: 14348,
    deal_score: -39,
    status: "listing",
    features: ["newest build (2020)", "sea view", "modern design"],
    listing_urls: [
      { site: "Spacious", url: "https://www.spacious.hk/en/hong-kong/n/28-discovery-bay/b/146984--discovery-bay-phase-16-poggibonsi-block-6" },
      { site: "28Hse", url: "https://www.28hse.com/en/new-properties/poggibonsi" }
    ],
    image_url: null,
  },
  {
    slug: "la-vista-3br",
    name: "La Vista - 3BR (Mar 13 txn)",
    phase: "Phase 7",
    estate: "La Vista",
    property_type: "Flat",
    beds: 3, baths: 2,
    gross_sqft: 1284, net_sqft: 1144,
    price: 12400000,
    psf_gross: 9657, psf_net: 10839,
    deal_score: 0,
    status: "transaction",
    features: ["recent transaction", "4 blocks estate"],
    listing_urls: [
      { site: "Spacious", url: "https://www.spacious.hk/en/hong-kong/n/28-discovery-bay/b/5257--la-vista" }
    ],
    image_url: null,
  },
  {
    slug: "la-vista-2br-premium",
    name: "La Vista - 2BR Premium (Mar 2 txn)",
    phase: "Phase 7",
    estate: "La Vista",
    property_type: "Flat",
    beds: 2, baths: 2,
    gross_sqft: 1011, net_sqft: 911,
    price: 16500000,
    psf_gross: 16319, psf_net: 18100,
    deal_score: 0,
    status: "transaction",
    features: ["premium unit", "possibly renovated", "high psf"],
    listing_urls: [
      { site: "Spacious", url: "https://www.spacious.hk/en/hong-kong/n/28-discovery-bay/b/5257--la-vista" }
    ],
    image_url: null,
  },
  {
    slug: "la-vista-mid",
    name: "La Vista - 3BR Mid (Feb 27 txn)",
    phase: "Phase 7",
    estate: "La Vista",
    property_type: "Flat",
    beds: 3, baths: 2,
    gross_sqft: 1202, net_sqft: 1054,
    price: 12000000,
    psf_gross: 9984, psf_net: 11400,
    deal_score: 0,
    status: "transaction",
    features: ["mid-range pricing", "good reference point"],
    listing_urls: [
      { site: "Spacious", url: "https://www.spacious.hk/en/hong-kong/n/28-discovery-bay/b/5257--la-vista" }
    ],
    image_url: null,
  },
  {
    slug: "amalfi",
    name: "Amalfi",
    phase: "Phase 14",
    estate: "Amalfi",
    property_type: "Flat",
    beds: 3, baths: 2,
    gross_sqft: 1200, net_sqft: null,
    price: 13500000,
    psf_gross: 11250, psf_net: null,
    deal_score: 0,
    status: "listing",
    features: ["newer development", "164 units", "HKR International"],
    listing_urls: [
      { site: "Spacious", url: "https://www.spacious.hk/en/hong-kong/n/28-discovery-bay/b/64607--amalfi-10c5ad21-5798-42fc-adbf-17501803e89d" }
    ],
    image_url: null,
  },
  {
    slug: "la-costa",
    name: "La Costa",
    phase: "Phase 8",
    estate: "La Costa",
    property_type: "Flat",
    beds: 3, baths: 2,
    gross_sqft: 1357, net_sqft: 1183,
    price: 23000000,
    psf_gross: 16949, psf_net: 19442,
    deal_score: -50,
    status: "listing",
    features: ["oceanfront", "wide sea view", "close to pier", "above budget"],
    listing_urls: [
      { site: "Spacious", url: "https://www.spacious.hk/en/hong-kong/n/28-discovery-bay/b/38075--dbay-la-costa-092554d1-a397-40fc-8c77-da9a92f18460" }
    ],
    image_url: null,
  },
];